server:
  port: 4010
spring:
  application:
    name: hrm-sysmanage
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/hrm-system?useUnicode=true&characterEncoding=utf8
    username: root
    password: sakura1993
mybatis-plus:
  type-aliases-package: com.hoki.zj.hrm.domain,com.hoki.zj.hrm.query
logging:
  level:
    com:
      hoki:
        zj: trace
    root: info
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:2010/eureka/
  instance:
    prefer-ip-address: true  #使用ip注册到Eureka
    instance-id: sysmanage-service:4010  #指定客户端实例的ID
feign:
  hystrix:
    enabled: true #开启熔断支持
  client:
    config:
      remote-service:           #服务名，填写default为所有服务
        connectTimeout: 3000
        readTimeout: 3000
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 3000