server:
  port: 5010
spring:
  application:
    name: hrm-file
logging:
  level:
    com:
      hoki:
        zj: trace
    root: info
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:2010/eureka/
  instance:
    prefer-ip-address: true  #使用ip注册到Eureka
    instance-id: auth-service:4020  #指定客户端实例的ID