server:
  port: 4010
spring:
  application:
    name: hrm-sysmanage
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/hrm-system?useUnicode=true&characterEncoding=utf8
    username: root
    password: sakura1993
mybatis-plus:
  type-aliases-package: com.hoki.zj.hrm.domain,com.hoki.zj.hrm.query
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:2010/eureka/
  instance:
    prefer-ip-address: true  #使用ip注册到Eureka
    instance-id: sysmanage-service:4010  #指定客户端实例的ID