server:
  port: 6010
spring:
  application:
    name: hrm-search
  data:
    elasticsearch:
      cluster-name: elasticsearch
      cluster-nodes: 127.0.0.1:9300 #9200是图形界面端,9300代码端
logging:
  level:
    com:
      hoki:
        zj: trace
    root: info
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:2010/eureka/
  instance:
    prefer-ip-address: true  #使用ip注册到Eureka
    instance-id: search-service:6010  #指定客户端实例的ID