server:
  port: 4070
spring:
  application:
    name: hrm-kill-pay
  rabbitmq:
    host: 127.0.0.1 # 主机
    port: 5672 # 端口
    username: guest # 用户名
    password: guest # 密码
    virtualHost: / # 虚拟机
    listener:
      simple:
        prefetch: 1 # 单个消费者每次获取的最大消息数
    publisher-confirms: true # 消息发送到交换机失败回调
    publisher-returns: true  # 消息发送到队列失败回调
    template:
      mandatory: true # 必须设置成true 消息路由失败通知监听者，而不是将消息丢弃
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/hrm-kill-pay?useUnicode=true&characterEncoding=utf8
    username: root
    password: sakura1993
  redis:
      database: 0
      host: 127.0.0.1
      port: 6379
      password: hOkI1993
      jedis:
        pool:
          max-wait: 2000ms
          min-idle: 2
          max-idle: 8
mybatis-plus:
  type-aliases-package: com.hoki.zj.hrm.domain,com.hoki.zj.hrm.query
  mapper-locations: com/hoki/zj/hrm/mapper/*Mapper.xml
logging:
  level:
    com:
      hoki:
        zj: trace
    root: info
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:2010/eureka/
  instance:
    prefer-ip-address: true  #使用ip注册到Eureka
    instance-id: kill-pay-service:4070  #指定客户端实例的ID
alibabapay:
  app-id: "2021000118608700"
  protocol: "https"
  gateway-host: "openapi.alipaydev.com"
  alibaba-public-key: "MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAmJv2ByIngiD50+ufYSCoDX3jqh/0L0ghOyaZ4g1wDD3fbjpFb19CmOe/k6V6pqiNgL2cAu+owT+9XN2rrNdmN6MV0oajQvtK2SSL5DCO+fuSLF4XY/UhsT53xKhwcAukr9kPzcyXTq4z6OjWPxtB3mSorS7pAnUST6MfLLf4bWnoEdvIqEmLf2xDe/4d0m8rLBVCebgdhYfeQN1b1d3Vy929dbF4JkD2WCo8MR9mSYwKFL7eAVlypntv3z5DS1DdGkPcuyOBU7NxmwQgawF8WZh1apTdXtMYOL6GEXgc0E1rz95fe7GxqN0Sqibhh+1suexRCrThQQaGothkcsRuuwIDAQAB"
  #商户私钥
  merchant-private-key: "MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCbvsDGjd8qzMjyhERHp1QEdfqjfcBzQ/WZT1ignigGUkXeZR0eRtgS45aVyIoi/prxdInE0aDqVtvsLTPeKL6QSbICYjUHtohnlRbJqZVY6X76sDOJfD1QMnQcdzi6x+R/YIT0bQul+gbheDYSVwgQXyyYvgMrA0J2U3crHsKrK7c0aYfbi2n4pcCW5EteqCecEVncrSMJL+0FOifrVeeXqUyczVH40Ee6zJPGzRykHoelULBDwOUkTx+IEbRaSaGQWpYfvS3+d7fgd5LVxRxJViDHRpr47ZWHxCAjJMyVeWVLJF/KzgPHwTV6QC5GpKiSYTLXDG9DOMU9Mb1Nw5NVAgMBAAECggEAWgUPd7RY4WwsWcCJlsDolwt6KzVsHzOQqWRrXasMh1rWd40KH43jJkfVqg2XilKPTDCH0PM5hzldNE2MRURXoR53fVk2PZcLkJNj8HvMju+nLU7a+wSMi+YdprZiW9NeByHKt1yv9udlQr0ww7j6ODxKkp6BRkNEDxB/OLU236gmDeqLKsSHAILjACkAzK3RhAb3oxMUiWtpW+cswvnoDhZJJXqbYZzIh6kfMk49FDgmZsE01oMcCwhRuI90kyvHJDnZxOHdgvgaj3l2k6yTMkWGUkGQLN84cpjDPYsgJlDiAIfAYWiO1gTx1XJ8V4t9UPnUsrqsO2AGS05ogZwNAQKBgQDJmTEdgBTYQs02yBlUZBveWgW5azeVPG565F4rImBoCL8FfrWLiWblCVHyuWuFUCHwLlHkc9+Z86yMussvEY/SJvJKOFrmn8cKZSKRXRq2qQ1gNabT8SwaNyHusd1NP2lFWeQnWvt/Rtfp0a8YdFQKHginZPL0eVMP/+Vw6Wa7yQKBgQDFxe2U3vPTsLJl/vAnwuyI70SWQ90XhzpRQtzm7ZH/UKSXtCc7Z4RZhrO631WzbO357OosREiKnw+zErAFkE5d0facQPIhfcs9kbAehhtLFndoHoT/pb06iEI91b50//vZG2j6y1lNGJftkYFyvxGZjvOsnG/iHvezUxvUeYaJLQKBgQC3v29q6hEVxF1zbxLXPp/AHOFWzYjN91Tjoj7KpfylFkO16HXkhwpH/CS7TZHY4t7sIev2hD7r/ZPqeV80uZcS/vib+Z2w0zUCHohRYkE0+AT/CifSyeFey52cCHYjMIbs9S/lRyIwMgweTEaBzZXD2vgcSwC/H847qQwhzDsdMQKBgCn5QNwImW0DIkmdWrDFoNfLGB5gFstIiur2KtXj88lg/x2nQXBNHvy1Ju3xOkoTQ0p4qpZsg4zQB0/1FmCH6OnmhtVQv1K2VO0jP2KrCZ3dDciOOaHcNhX3Fz/yXjKMpZHFTHl1sOU44/2qlPOac4zIlxS6OtCdy+pGKDDm/dOdAoGACIkidM7RJbRMpVCqm/rzepf3/QlsXa1vjMNp+lQm8c3GGKE0uncLug+AztYo70GLmI3FPxx+Wg/TJaCeLsK4Rs+pMeIW1d9kx2i67f+OqMvsfH67invghfCwh8eE6qcdI8YHbzmq+M9/XkPW+Cr4R7/yc9NpgImk5YWpHSLfI5U="
  sign-type: "RSA2"
  notify-url: "http://hoki.free.svipss.top/services/killPay/pay/notify"
  return-url: "http://localhost:3010/services/killPay/pay/return"